config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'admin', to: 'authentication#new'
  post 'admin', to: 'authentication#create'
  get 'sign-out', to: 'authentication#destroy', as: 'signout'

  resources :articles
  resources :categories

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :combinations
  has_many :categories, through: :combinations
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/article_category.rb
class Combination < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :combinations
  has_many :articles, through: :combinations
end

app/models/combination.rb
class Combination < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  
  def ensure_current_user
      unless current_user
        flash[:notice] = 'You forgot to sign in....'
        redirect_to root_path
      end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id].present?
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :ensure_current_user

  def index
    @articles = Article.all
    @categories = Category.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "#{@article.title} was saved!"
      redirect_to articles_path
    else
      flash[:danger] = 'Uh-oh, this did not work.  Did you enter all the correct fields?'
      render :new
    end
  end

  def show
    @article = Article.find(params[:id])
    @categories = @article.categories
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to articles_path
    else
      render :edit
    end
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy
    flash[:notice] = "Article: '#{article}' was deleted from the database"
    redirect_to articles_path
  end


  private

  def article_params
    params.require(:article).permit(:title, :link, :label_order, :category, :blurb, :avatar)
  end

end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Good job #{user.username.capitalize}, you have signed into your website"
      redirect_to articles_path
    else
      flash[:danger] = 'Bad Gloma.  Try again'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'You have successfully signed out.'
    redirect_to root_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :ensure_current_user
  
  def index
    @categories = Category.all
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :index
    end
  end

  def update
    @category = Category.find([:id])
    if @category.update(category_params)
      redirect_to categories_path
    else
      render :index
    end
  end


  private

  def category_params
    params.require(:category).permit(:category_name)
  end

end

app/controllers/structures_controller.rb
class StructuresController < ApplicationController
  before_action :ensure_current_user
  def index
    @articles = Article.all.order(:category)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "#{@article.title} was saved!"
      redirect_to structures_path
    else
      flash[:danger] = 'Uh-oh, this did not work.  Did you enter all the correct fields?'
      render :new
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to structure_path(@article)
    else
      render :edit
    end
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy
    flash[:notice] = "Article: '#{article}' was deleted from the database"
    redirect_to structures_path
  end


  private

  def article_params
    params.require(:article).permit(:title, :link, :label_order, :category, :blurb)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController <ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:username, :password))
      if @user.save
        flash[:notice] = 'Congrats Gloma, you have successfully signed in'
        redirect_to root_path
      else
        flash[:danger] = 'Gloma, you spelled something wrong...'
        render :index
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<h1><%= button_nm %></h1>

<%= form_for @article do |f| %>
  <div class='form-horizontal'>
    <div class='form-group'>
      <%= f.label :title, class: "col-md-2 control-label" %>
      <div class='col-md-5'>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
    </div>

    <div class='form-group'>
      <%= f.label :link, class: "col-md-2 control-label" %>
      <div class='col-md-5'>
        <%= f.text_field :link, class: 'form-control' %>
      </div>
    </div>

    <div class='form-group'>
      <%= f.label :label_order, class: "col-md-2 control-label" %>
      <div class='col-md-5'>
        <%= f.number_field :label_order, class: 'form-control' %>
      </div>
    </div>

    <div class='form-group'>
      <%= f.label :category_id, class: "col-md-2 control-label" %>
      <div class='col-md-5'>
        <%= collection_select :article, :category_id, Category.all, :id, :category_name, {:selected => 1}, {class: 'form-control'} %>
      </div>
    </div>

    <div class='form-group'>
      <%= f.label :blurb, class: "col-md-2 control-label" %>
      <div class='col-md-5'>
        <%= f.text_area :blurb, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :avatar, class: 'col-md-2 control-label' %>
      <div class="col-md-5">
        <%= f.file_field :avatar, class: 'form-control' %>
      </div>
    </div>

    <div class='form-group'>
      <div class='col-md-offset-2 col-md-10'>
        <%= f.submit button_nm, class: 'btn btn-primary' %>
        <%= link_to 'Cancel', articles_path, class: 'btn btn-default' %>

        <% if controller.action_name == 'edit'  %>
        <%= link_to 'Delete Article', article_path, method: :delete, class:'btn btn-danger' %>
        <% end %>
      </div>
    </div>

  </div>
<% end %>

app/views/articles/edit.html.erb
<%= render partial: 'form', locals:{button_nm: 'Update Article'} %>

app/views/articles/index.html.erb
<%= link_to 'Sign out', signout_path %>

<div class='page-header'>
  <div class='text-right'>
    <%= link_to 'New Article', new_article_path, class:'btn btn-primary pull-right' %>
    <%= link_to 'New Category', categories_path, class:'btn btn-info pull-right' %>
  </div>
  <h1>Articles listed on Gloma</h1>
</div>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Update</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= link_to article.title, article_path(article) %> </td>
        <td><%= link_to "Edit", edit_article_path(article), class:'btn btn-info' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/new.html.erb
<%= render partial: 'form', locals:{button_nm: 'Create Article'} %>

app/views/articles/show.html.erb
<div class="page-header">
  <h1>Title: <%= @article.title %></h1>
</div>
<div class="container">
  <div class="col-md-offset-2 col-md-8">
    <div class="well">
      <div class="form-group">
        <b>Article Link:</b>
        <%= @article.link %>
      </div>
      <div class="form-group">
        <b>Article Label Order:</b>
        <%= @article.label_order %>
      </div>
      <div class="form-group">
        <b>Article Categories:</b>
        <% @categories.each do |category| %>
          <%= category.category_name %>, 
        <% end %>
      </div>
      <div class="form-group">
        <b>Article Blurb:</b>
        <%= @article.blurb %>
      </div>
      <div class="form-group">
        <b>Article Image:</b>
        <%= image_tag @article.avatar.url(:medium) %>
      </div>
    </div>
  </div>
</div>

app/views/authentication/new.html.erb
<div class="container">
  <div class='col-md-offset-3 col-md-6'>
    <div class='well'>
      <div class='page-header'>
        <h1>Admin Sign In</h1>
          <br>
          <%= form_tag admin_path do |f| %>
            <div class='form-group'>
              <%= label_tag :username, 'Username', class: "control-label" %>
              <%= text_field_tag :username, '', class: "form-control" %>
            </div>
            <div class="form-group">
              <%= label_tag :password, 'Password', class:"control-label" %>
              <%= password_field_tag :password, '', class:"form-control" %>
            </div>
            <div class="form-group">
              <%= submit_tag "Sign In", class:'btn btn-primary' %>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<%= link_to 'Sign out', signout_path %>

<div class='page-header'>
  <h1>Categories listed on Gloma</h1>
</div>

<%= form_for @category do |f| %>
  <div class='form-group'>
    <%= f.label :category_name, class: 'col-md-2 control-label' %>
    <div class='col-md-5'>
      <%= f.text_field :category_name, class: 'form-control' %>
    </div>
    <%= f.submit "Create Category", class:'btn btn-info' %>
  </div>
<% end %>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
    <tr>
      <td><%= category.category_name %> </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yay for Gloma</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <%= link_to "Gloria Kestenbaum", root_path, class:"navbar-brand" %>
      </div>
    </div>
  </nav>
  <div class="container">
    <!-- Adding create/update/destroy task note if relevant -->
    <% if notice %>
      <p class="alert alert-success" role="alert"><%= flash[:notice] %></p>
    <% end %>

    <%= yield %>

    <div class="page-header">
    </div>

    <footer class="footer">

      <div class="col-md-9">
        <%= link_to "Home", root_path %>
      </div>

      <div class="col-md-3 text-right">
        <%=link_to "https://www.linkedin.com/pub/gloria-kestenbaum/0/aa1/48" do %>
        <%=image_tag("linkedin.jpg", height:"25")%>
        <%end%>
      </div>
    </footer>

  </div>

</body>
</html>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1>Herro, I am Gloma.</h1>
  <p>blah blah blah blah blah...blah blah blah blah blah...blah blah blah blah blah...blah blah blah blah blah...blah blah blah blah blah...blah blah blah blah blah...</p>
  <p><a class="btn btn-primary btn-lg" href="#" role="button">Click on me for giggles</a></p>
</div>